include:
  - project: 'e/os/releases'
    ref: master
    file: '/templates/.gitlab-ci.yml'

update-manifest-r:
  extends: .update-manifest

check-version:
  extends: .check-version

trigger-build-r-dev:
  extends: .trigger-build-dev
  variables:
    DEVICES: "a5y17lte a7y17lte ahannah akari akatsuki apollon aura bacon bardock bardockpro beckham beryllium beyond0lte beyond1lte beyond2lte beyondx blueline bonito cedric channel cheeseburger chef cheryl chiron crosshatch d1 d2s d2x d800 d801 d802 d803 d850 d851 d852 d855 dipper discovery dumpling enchilada ether evert f400 fajita flame flox FP2 FP3 FP4 gemini gta4xlwifi gts4lv gts4lvwifi guacamole h850 h910 h918 h990 hannah hletmo hlte hltechn hltekor hotdog hotdogb instantnoodle instantnoodlep jactivelte jasmine_sprout jason jflteatt jfltespr jfltevzw jfvelte kirin klte klteactivexx klteaio kltechn kltechnduo klteduos kltedv kltekdi kltekor kuntao lake lavender lithium lmi ls990 ls997 m20lte mata mermaid miatoll montana nash natrium ocean onclite oneplus3 payton pioneer PL2 platina polaris pro1 rhannah river rs988 sagit sargo scorpio shamu sunfish suzuran taimen us996 victara voyager vs985 vs995 walleye whyred X00TD X01AD X01BD x2 xz2c YTX703F YTX703L Z01R z2_plus z3 z3c zippo zl1"

trigger-build-r-stable:
  extends: .trigger-build-stable
  variables:
    DEVICES: "FP4"
