include:
  - project: 'e/os/releases'
    ref: master
    file: '/templates/.gitlab-ci.yml'

update-manifest-r:
  extends: .update-manifest

check-version:
  extends: .check-version

trigger-build-r-dev:
  extends: .trigger-build-dev
  variables:
    DEVICES: "a5y17lte a7y17lte ahannah akari akatsuki apollon aura bacon bardock bardockpro beckham beryllium beyond0lte beyond1lte beyond2lte beyondx blueline bonito cedric channel cheeseburger chef cheryl chiron crosshatch d1 d2s d2x d800 d801 d802 d803 d850 d850 d851 d852 d855 dipper discovery dumpling ether evert f400 flame flox FP2 FP3 gemini gta4xlwifi gts4lv gts4lvwifi guacamole h850 h910 h918 h990 hlte jactivelte jasmine_sprout jason kirin klte klteactivexx kuntao lavender lithium m20lte mata mermaid miatoll nash natrium onclite payton pioneer polaris river sagit scorpio shamu sunfish taimen victara voyager whyred X00TD X01BD x2 z2_plus z3c zl1"
