include:
  - project: 'e/os/releases'
    ref: master
    file: '/templates/.gitlab-ci.yml'

update-manifest-r:
  extends: .update-manifest

check-version:
  extends: .check-version

trigger-build-r-dev:
  extends: .trigger-build-dev
  variables:
    DEVICES: "ahannah akari akatsuki apollon aura bacon beckham beryllium beyond0lte beyond1lte beyond2lte beyondx cheeseburger chiron dumpling FP2 FP3 guacamole lavender lithium mata river scorpio shamu sunfish whyred"
