include:
  - project: 'e/os/releases'
    ref: master
    file: '/templates/.gitlab-ci.yml'

update-manifest-q:
  extends: .update-manifest

check-version:
  extends: .check-version

trigger-build-q-test:
  extends: .trigger-build-test
  variables:
    DEVICES: "beryllium chiron crownlte FP2 FP3 GS290 guacamole guacamoleb lavender lithium marlin mata river sailfish scorpio shamu star2lte starlte tissot whyred"

trigger-build-q-dev:
  extends: .trigger-build-dev
  variables:
    DEVICES: "beryllium chiron crownlte enchilada fajita FP2 FP3 GS290 guacamole guacamoleb lake lavender lithium marlin mata oneplus2 oneplus3 river sailfish scorpio shamu star2lte starlte tissot"

trigger-build-q-stable:
  extends: .trigger-build-stable
  variables:
    DEVICES: "FP3 GS290"
