include:
  - project: 'e/os/releases'
    ref: master
    file: '/templates/.gitlab-ci.yml'

update-manifest-q:
  extends: .update-manifest

check-version:
  extends: .check-version

trigger-build-q-test:
  extends: .trigger-build-test
  variables:
    DEVICES: "beryllium chiron crownlte FP2 FP3 GS290 guacamole guacamoleb lavender lithium marlin mata river sailfish scorpio shamu star2lte starlte tissot whyred"

trigger-build-q-dev:
  extends: .trigger-build-dev
  variables:
    DEVICES: "a3xelte a5xelte a5y17lte a7y17lte bacon beryllium cheeseburger cheryl chiron crownlte d802 d855 dipper discovery dumpling enchilada evert fajita FP2 FP3 GS290 gemini ginkgo gts4lvwifi guacamole guacamoleb griffin h850 harpia hlte I01WD jactivelte jasmine_sprout jason jfltexx kirin lake lavender lilac lithium lux m8 m8d marlin mata mermaid nash natrium onclite oneplus2 oneplus3 osprey payton pioneer polaris river s3ve3gds s3ve3gjv s3ve3gxx s5neolte sagit sailfish scorpio shamu star2lte starlte suzuran taimen tissot twolip voyager wt88047 wayne whyred x2 z3c"

trigger-build-q-stable:
  extends: .trigger-build-stable
  variables:
    DEVICES: "FP3 GS290"
