include:
  - project: 'e/os/releases'
    ref: master
    file: '/templates/.gitlab-ci.yml'

update-manifest-r:
  extends: .update-manifest

check-version:
  extends: .check-version

trigger-build-r-dev:
  extends: .trigger-build-dev
  variables:
    DEVICES: "a5y17lte a7y17lte ahannah akari akatsuki apollon aura bacon beckham beryllium beyond0lte beyond1lte beyond2lte beyondx blueline bonito cedric channel cheeseburger cheryl chiron crosshatch d1 d2s d2x d800 d801 d802 d803 d850 d851 d852 d855 dipper discovery dumpling ether evert f400 flame flox FP2 FP3 gemini gta4xlwifi gts4lvwifi guacamole h850 h990 hlte jactivelte jasmine_sprout jason kirin lavender lithium m20lte mata mermaid miatoll nash natrium onclite payton pioneer polaris river sagit scorpio shamu sunfish taimen voyager whyred x2 z3c zl1"
