include:
  - project: 'e/os/releases'
    ref: master
    file: '/templates/.gitlab-ci.yml'

update-manifest-q:
  extends: .update-manifest

check-version:
  extends: .check-version

trigger-build-q-test:
  extends: .trigger-build-test
  variables:
    DEVICES: "beryllium chiron crownlte FP2 FP3 GS290 guacamole guacamoleb lavender lilac lithium marlin mata river sailfish scorpio shamu star2lte starlte suzuran tissot whyred z3c"

trigger-build-q-dev:
  extends: .trigger-build-dev
  variables:
    DEVICES: "a3xelte a5xelte bacon beryllium cheeseburger chiron crownlte dipper discovery dumpling enchilada evert fajita FP2 FP3 GS290 gemini ginkgo gts4lvwifi guacamole guacamoleb griffin harpia hlte jactivelte jasmine_sprout jason jfltexx kirin lake lavender lilac lithium lux m8 marlin mata mermaid nash natrium onclite oneplus2 oneplus3 osprey payton pioneer polaris river s3ve3gds s3ve3gjv s5neolte sagit sailfish scorpio shamu star2lte starlte suzuran taimen tissot twolip voyager wayne whyred z3c"

trigger-build-q-stable:
  extends: .trigger-build-stable
  variables:
    DEVICES: "FP3 GS290"
