variables:
  BRANCHES: "v1-nougat v1-oreo v1-pie"

stages:
  - manifest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git remote set-url origin ssh://git@gitlab.e.foundation:2222/$CI_PROJECT_PATH.git
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global user.email "$GITLAB_USER_EMAIL"

.update-manifest:
  image:
    name: "registry.gitlab.e.foundation:5000/e/os/docker-lineage-cicd:prod"
    entrypoint: [""]
  stage: manifest
  script:
    - cd "$SRC_DIR/$CI_COMMIT_REF_NAME"
    - repo init -u $REPO -b $CI_COMMIT_REF_NAME
    - repo sync -c --force-sync --prune
    - repo manifest -o $CI_PROJECT_DIR/default.xml
    - cd $CI_PROJECT_DIR
    - git add .
    - git commit -m "Update $CI_COMMIT_REF_NAME manifest" || true
    - git push origin HEAD:$CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
  tags:
    - generate-e-manifest
