name: Sync GitLab changes to GitHub

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name MikuX-Dev
          git config --global user.email abinishanth3464@gmail.com

      - name: Fetch GitLab changes
        run: git remote add gitlab https://gitlab.e.foundation/e/os/releases.git && git fetch gitlab

      - name: Push changes to GitHub
        run: |
          git remote set-url origin https://github.com/MikuX-Dev/local-manifest.git
          git push origin gitlab/master:master
  
